#!/bin/sh
xrandr --output HDMI1 --off --output LVDS1 --mode 1280x800 --pos 2560x800 --rotate normal --output DP1 --mode 2560x1600 --pos 0x0 --rotate normal --output VGA1 --off
bash ~/bin/make_monitor_primary
xmodmap ~/.xmodmap
