#!/usr/bin/bash

if [[ $1 == "startup" ]]; then
  gnome-settings-daemon &

  # docks
  xmobar &
  killall trayer
  trayer --edge top --align right --SetDockType true --SetPartialStrut true  --width 10 --transparent true --tint 0x000000 --height 24 &

  guake &

  # network manager
  nm-applet &

  # lock screen
  gnome-screensaver &

  # hide mouse when its not moving
  unclutter -noevents -root -grab&
fi
