#!/usr/bin/bash

function run_if_not {
  pgrep $1 || $*
}

if [[ $1 == "startup" ]]; then
  /usr/bin/setxkbmap -option 'ctrl:nocaps'
  xmodmap ~/.xmodmap

  cinnamon-settings-daemon &
  gnome-panel &

  run_if_not nautilus -n &
  # Apps
  run_if_not workrave &
  killall synapse
  synapse -s &

  # network manager
  killall nm-applet 
  run_if_not nm-applet &

  # lock screen
  run_if_not cinnamon-screensaver &

  # docks
  run_if_not xmobar &

  # onboard
  run_if_not onboard &

  export SSH_ASKPASS="/usr/bin/ssh-askpass"
  ssh-add &


  # Add --monitor 1 or 0 to change where it appears
#  killall trayer
#  run_if_not trayer --edge top --align right --SetDockType true --SetPartialStrut true  --width 11 --transparent true --tint 0x000000 --height 32 &

  killall ginn
  run_if_not ginn /etc/ginn/wishes.xml &

  run_if_not xcompmgr -n &
  run_if_not unclutter -idle 0.1 &

  hsetroot -solid "#000000" &


  /usr/bin/setxkbmap -option 'ctrl:nocaps' &
  xmodmap ~/.xmodmap &

fi
